language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip wheel setuptools
  - pip install cython
  - pip install -r requirements.txt
  - pip install .

script: python -m unittest discover -v
