language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install .
script: python -m unittest discover -v
